### ISSUE TITLE
'Run' tab becomes unresponsive after shutting down an instance

### ISSUE THREAD

**Issue by Xarthisius** [whole-tale/dashboard#185]
Step to reproduce:
1. Login and launch a Tale (from 'browse' view)
2. Go to 'Run', select an Instance from right panel, delete instance
3. Go to different tab, then try to go back to 'Run'

This traceback might be relevant:

```
vendor-4c400ad00abf6b6ac14145a470b715f2.js:1859 Error while processing route: run.view Attempted to handle event `loadingData` on <instance:5b3b7bb08b0b4b0001c0189f> while in state root.deleted.saved. Called with {_id: 2957, _label: Fetching instance' with id: 5b3b7bb08b0b4b0001c0189f, _state: undefined, _result: undefined, _subscribers: }. Error: Attempted to handle event `loadingData` on <instance:5b3b7bb08b0b4b0001c0189f> while in state root.deleted.saved. Called with {_id: 2957, _label: Fetching instance' with id: 5b3b7bb08b0b4b0001c0189f, _state: undefined, _result: undefined, _subscribers: }.
    at new n (https://newdashboard.dev.wholetale.org/assets/vendor-4c400ad00abf6b6ac14145a470b715f2.js:1866:13)
    at e._unhandledEvent (https://newdashboard.dev.wholetale.org/assets/vendor-4c400ad00abf6b6ac14145a470b715f2.js:10015:121)
    at e.send (https://newdashboard.dev.wholetale.org/assets/vendor-4c400ad00abf6b6ac14145a470b715f2.js:10004:19)
    at e.loadingData (https://newdashboard.dev.wholetale.org/assets/vendor-4c400ad00abf6b6ac14145a470b715f2.js:10001:253)
    at o._scheduleFetch (https://newdashboard.dev.wholetale.org/assets/vendor-4c400ad00abf6b6ac14145a470b715f2.js:10165:10)
    at o._findRecord (https://newdashboard.dev.wholetale.org/assets/vendor-4c400ad00abf6b6ac14145a470b715f2.js:10155:190)
    at o.findRecord (https://newdashboard.dev.wholetale.org/assets/vendor-4c400ad00abf6b6ac14145a470b715f2.js:10155:49)
    at o.model (https://newdashboard.dev.wholetale.org/assets/wholetale-264c0f35f30555a73a1c04a0621bc4be.js:568:1255)
    at o.n [as model] (https://newdashboard.dev.wholetale.org/assets/vendor-4c400ad00abf6b6ac14145a470b715f2.js:3148:9)
    at o.deserialize (https://newdashboard.dev.wholetale.org/assets/vendor-4c400ad00abf6b6ac14145a470b715f2.js:2694:121)
```

Also I noticed that 'Run' link from the top navbar contain instanceId (https://newdashboard.dev.wholetale.org/run/5b3b7a998b0b4b0001c01874) that stays even if hard refresh.

**Comment by ThomasThelen** [comment]
I tested this in `5eae564` (15-November-2018) and can't reproduce the issue. I can confirm that @swyngaard's comment is still relevant.
