### ISSUE TITLE
Andromeda Tale doesn't seem to load

### ISSUE THREAD

**Issue by setgree** [whole-tale/dashboard#220]
Launch 'Andromeda Image', click through to `/data` : 

```
Server error: Traceback (most recent call last): 
File "/opt/conda/lib/python3.6/site-packages/tornado/web.py", line 1592, in _execute result = yield result 
File "/opt/conda/lib/python3.6/site-packages/tornado/gen.py", line 1133, in run value = future.result() 
File "/opt/conda/lib/python3.6/site-packages/tornado/gen.py", line 326, in wrapper yielded = next(result) 
File "/opt/conda/lib/python3.6/site-packages/notebook/services/contents/handlers.py", line 112, in get path=path, type=type, format=format, content=content,
File "/opt/conda/lib/python3.6/site-packages/notebook/services/contents/filemanager.py", line 431, in get model = self._dir_model(path, content=content) 
File "/opt/conda/lib/python3.6/site-packages/notebook/services/contents/filemanager.py", line 313, in _dir_model for name in os.listdir(os_dir): OSError: [Errno 14] Bad address: '/home/jovyan/work/data' 
```

**Comment by Xarthisius** [comment]
Thanks for the report! We recently identified that bug (https://github.com/whole-tale/girder_wholetale/issues/121) and fixed that in our development branch (https://github.com/whole-tale/girder_wholetale/pull/124). We're going to include it in our next release (in ~2 weeks).
In the meantime. I applied a workaround for our current production. Tale should work now. Please let us know if that's not the case.
