### ISSUE TITLE
Bad state when registering and deleting datasets quickly in succession

### ISSUE THREAD

**Issue by bodom0015** [whole-tale/dashboard#427]
## Steps to Reproduce
1. Refresh the page
2. Delete a dataset (before registering a new one)
3. Without refreshing, register/reassociate a dataset (e.g. one that does not already appear in the view)
    * You'll see the 400 errors in the console
    * The view won't update properly, and newly registered data is never shown
4. Click the Home nav, then click back to Data

### Expected Results
* Home folder should be shown after navigating away
* User's Registered Datasets should be shown after navigating back
* No error messages appear in the console

### Actual Results
* Home folder is shown when navigating away
* When navigating back, the Home folder is cleared from view but User's Registered Data list never displays
* No error messages appear in the console
* Only a hard refresh can correct this state - navigating to Run and back or changing navs does not correct the issue

#### Possible Explanation
Closest I can tell so far, something outside of the folder nav service is still not handling undefined properly. Those 400s are coming back from `GET /api/folder`, which appears to be coming from the `refresh()` function inside the `manage/left-panel` component.

More investigation is needed to figure out exactly what is happening there

**Comment by bodom0015** [comment]
Still looking into this one, and I think I've tracked it down... when we hit the error state, it seems that we are actually winding up in this error-handler: https://github.com/whole-tale/dashboard/blob/master/app/components/dashboard/manage/left-panel/component.js#L163-L165

It would seem that I forgot to fill out this `.catch()` handler, which currently prints nothing and then returns. As a result, we never hit the `.then()` above, and never see the new dataset list added.

The error stacktrace that was being suppressed, is the same familiar one that we've seen when calling delete a model that was fetched with `reload` / `backgroundReload` set to `true`:
```
"Error: Attempted to handle event `pushedData` on <dataset:5c5cad3573e02b0001349a06> while in state root.deleted.saved. 
    at new n (https://dashboard.local.wholetale.org/assets/vendor-3fec92aafa2a46ab1024fb73ecea7c3c.js:1867:13)
    at e._unhandledEvent (https://dashboard.local.wholetale.org/assets/vendor-3fec92aafa2a46ab1024fb73ecea7c3c.js:10849:121)
    at e.send (https://dashboard.local.wholetale.org/assets/vendor-3fec92aafa2a46ab1024fb73ecea7c3c.js:10838:19)
    at e.pushedData (https://dashboard.local.wholetale.org/assets/vendor-3fec92aafa2a46ab1024fb73ecea7c3c.js:10835:429)
    at e.setupData (https://dashboard.local.wholetale.org/assets/vendor-3fec92aafa2a46ab1024fb73ecea7c3c.js:10835:86)
    at o._load (https://dashboard.local.wholetale.org/assets/vendor-3fec92aafa2a46ab1024fb73ecea7c3c.js:11047:10)
    at o._pushInternalModel (https://dashboard.local.wholetale.org/assets/vendor-3fec92aafa2a46ab1024fb73ecea7c3c.js:11066:12)
    at https://dashboard.local.wholetale.org/assets/vendor-3fec92aafa2a46ab1024fb73ecea7c3c.js:11063:24
    at e._run (https://dashboard.local.wholetale.org/assets/vendor-3fec92aafa2a46ab1024fb73ecea7c3c.js:1664:94)
    at e._join (https://dashboard.local.wholetale.org/assets/vendor-3fec92aafa2a46ab1024fb73ecea7c3c.js:1663:327)"
```

As with the bug's previous occurrences, I do not know of a way to fix this once it occurs without refreshing the view.

**Comment by bodom0015** [comment]
This will likely need the same type of fix as was used in #610 ...
